# templates/apache-deployment.yaml 최종 수정본
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apache-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apache
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apache
    spec:
      containers:
      - name: apache
        image: {{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}
        ports:
        - containerPort: {{ .Values.apache.service.port }}
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ default "" .Values.aws.accessKey | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ default "" .Values.aws.secretKey | quote }}
        - name: AWS_REGION
          value: {{ default "us-east-2" .Values.aws.region | quote }}
        - name: BUCKET_NAME
          value: {{ default "" .Values.aws.bucketName | quote }}
