apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache-service
spec:
  type: {{ .Values.apache.service.type }}
  ports:
  - port: {{ .Values.apache.service.port }}
    targetPort: {{ .Values.apache.service.port }}
  selector:
    app: {{ .Release.Name }}-apache


apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-service
spec:
  type: {{ .Values.spring.service.type }}
  ports:
  - port: {{ .Values.spring.service.port }}
    targetPort: {{ .Values.spring.service.port }}
  selector:
    app: {{ .Release.Name }}-spring