# templates/spring-deployment.yaml [7] 수정
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-spring
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-spring
    spec:
      serviceAccountName: {{ include "didle-app.serviceAccountName" . }} # <--- 이 줄 추가
      containers:
        - name: spring
          image: {{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag }}
          ports:
            - containerPort: {{ .Values.spring.service.port }}
          env:
            - name: AWS_REGION
              value: {{ default "us-east-2" .Values.aws.region | quote }}
            - name: BUCKET_NAME
              value: {{ default "didle-service-data" .Values.aws.bucketName | quote }}
          # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY는 여기서 제거 (IRSA 사용)
