apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-spring
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-spring
    spec:
      containers:
      - name: spring
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.aws.accessKey | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.aws.secretKey | quote }}
        - name: AWS_REGION
          value: {{ .Values.aws.region | quote }}
        - name: BUCKET_NAME
          value: {{ .Values.aws.bucketName | quote }}
